apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sub-flood-ssd-gitlab-runner-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 50Gi

